---
# Ingress is an API object that manages external access to the services in a cluster, typically HTTP.
# Ingress exposes HTTP and HTTPS routes from outside the cluster to services within the cluster.
# Traffic routing is controlled by rules defined on the Ingress resource. You can see Ingress as directly connected
# to a Service. Cargo is using NGINX Ingress Controller
# Configures a load balancer or proxy server

# ! Use this file if your cluster is only internally reachable, meaning it has a cargo.stxt.media.int ending.
# It will secure your website with an internal certificate.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cargo-demo-ingress                                    # Ingress name
  namespace: cargo-demo
  labels:
    app: cargo-demo
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"    # Advise to redirect all HTTP Traffic to HTTPS
spec:
  rules:
  - host: cargo-demo1.cargo-purple.cargo.stxt.media.int          # ! Please adapt this to your settings!
    http:
      paths:
      - path: /                                               # The path must match the content of an incoming request
        pathType: Prefix                                      # Match all paths (with / prefix)
        backend:                                              # A backend is a combination of Service and port names
          service:
            name: cargo-demo                                  # Connect to the cargo-demo Service ...
            port:
              number: 8088                                    # ... on Port 8088
