---
# a StatefulSet manages Pods that are based on an identical container spec. Unlike a Deployment, a StatefulSet maintains a sticky identity for each of their Pods.
# f you want to use storage volumes to provide persistence for your workload, you can use a StatefulSet as part of the solution
# You can use stateful sets if you need
# - stable, unique network identifiers
# - stable, persistent storage
# - ordered, graceful deployments and scaling
# - ordered automated rolling updates

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis                                # has to match .spec.template.metadata.labels
  serviceName: "redis"
  replicas: 1                                   # by default 1
  template:
    metadata:
      labels:
        app: redis                              # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10         # Wait 10 seconds for a succesful shutdown
      containers:
      - name: redis
        image: bitnami/redis:5.0.7
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
        resources:
          requests:                           # requests will make sure the pod is deployed on a node that has ...
            memory: 5Mi                       # 20Mi memory and ...
            cpu: 5m                           # 100m CPU available.
          limits:                             # This pod is not allowed to use more than ...
            memory: 50Mi                      # 200Mi memory and ...
            cpu: 50m                          # 250m CPU
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]         # Chose one of the possible access modes
      storageClassName: "nas-perf"             # There are 4 different storage classes available (see docu)
      resources:
        requests:
          storage: 1Gi                         # Size of the PVC
