---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cargo-demo
  namespace: cargo-demo
spec:
  selector:
    matchLabels:
      app: cargo-demo
  endpoints:
  - port: http
    path: /metrics
    interval: 5m
