---
# A ServiceMonitor describes the set of targets to be monitored by Prometheus.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cargo-demo
  namespace: cargo-demo
spec:
  selector:
    matchLabels:
      app: cargo-demo
  endpoints:
  - port: http                            # Our app exposes metrics on port named http
    path: /metrics                        # Path where the endpoint is exposed
    interval: 10s                         # scraping interval for prometheus
